name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install and Build
      run: |
        npm ci
        npx vite build
        
    - name: Prepare deployment package
      run: |
        cat > server.js << 'EOF'
        const express = require('express');
        const path = require('path');
        const app = express();
        app.use(express.static('dist'));
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname, 'dist', 'index.html'));
        });
        app.listen(process.env.PORT || 8080);
        EOF
        
        cat > package.json << 'EOF'
        {
          "name": "tsv-rot-app",
          "scripts": {
            "start": "node server.js"
          },
          "dependencies": {
            "express": "^4.18.2"
          }
        }
        EOF
        
        npm install express --production
        rm -rf node_modules/.cache
        rm -rf node_modules/.bin
        
    - name: Create deployment artifact
      run: zip -r deploy.zip dist/ server.js package.json node_modules/express/ -x "*.map" -x "*.md"
      
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tsvrot-trainer-2025'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip
