name: Deploy TSV Rot Trainer to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install and Build
      run: |
        npm ci
        npm run build

    - name: Prepare deployment files
      run: |
        cat > package.json << 'EOF'
        {
          "name": "tsvrot-trainer",
          "version": "1.0.0",
          "scripts": {
            "start": "serve dist -s -l 8181"
          },
          "dependencies": {
            "serve": "^14.2.1"
          }
        }
        EOF
        
        npm install serve --production

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'tsvrot-trainer-2025'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
