name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build with npx
      run: npx vite build
      
    - name: Add server.js
      run: |
        cat > server.js << 'EOF'
        const express = require('express');
        const path = require('path');
        const app = express();
        app.use(express.static('dist'));
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname, 'dist', 'index.html'));
        });
        app.listen(process.env.PORT || 8080);
        EOF
        
    - name: Add start script to package.json
      run: |
        npm pkg set scripts.start="node server.js"
        npm install express --save
      
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tsvrot-trainer-2025'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
